#ansible-playbook fifth.yml --tag install
#ansible-playbook fifth.yml --tag remove
---
 - name: Running Playbook
   hosts: all
   become: yes
   #gather_facts: false
   tasks:
           - name: Installing packages on Ubuntu
             apt:
              name: "{{ item }}"
              state: present
             loop:
                     - wget
                     - vim
                     - apache2
                     - tcpdump
                     - nano
                     - iptables
                     - procps
                     - git
                     - curl
                     - net-tools
                     - iputils-ping
                     - rsync

             when: ansible_distribution == "Ubuntu"
             tags: install

           - name: Installing packages
             yum:
              name: "{{ item }}"
              state: present
             loop:
                     - wget
                     - vim
                     - httpd
                     - tcpdump
                     - nano
                     - iptables
                     - procps
                     - git
                     - curl
                     - net-tools
                     - iputils
                     - rsync

             when: ansible_distribution == "Amazon"
             tags: install

           - name: Removing packages on Ubuntu
             apt:
              name: "{{ item }}"
              state: absent
             loop:
                     - wget
                     - vim
                     - apache2
                     - tcpdump
                     - nano
                     - iptables
                     - procps
                     - git
                     - curl
                     - net-tools
                     - iputils-ping
                     - rsync

             when: ansible_distribution == "Ubuntu"
             tags: remove

           - name: Removing packages
             yum:
              name: "{{ item }}"
              state: absent
             loop:
                     - wget
                     - vim
                     - httpd
                     - tcpdump
                     - nano
                     - iptables
                     - procps
                     - git
                     - net-tools
                     - iputils
                     - rsync

             when: ansible_distribution == "Amazon"
             tags: remove


