#ansible-playbook sixth.yml --tag configure
#ansible-playbook sixth.yml --tag remove
---
 - name: This playbook for doing all web server releated task
   hosts: ubuntuhost
   become: yes
   vars:
           server_name: Prod Server
           owner: Nidhi my love
   tasks:
           - name: Installing apache2
             apt: name=apache2 state=present
             tags: configure

           - name: Starting apache2
             service: name=apache2 state=started
             tags: configure

           - name: copy index file
             template: src=index.j2 dest=/var/www/html/index.html
             tags: configure

           - name: Stopping the apache2
             service: name=apache2 state=stopped
             tags: remove

           - name: Uninstalling apache2 
             apt: name=apache2 state=absent
             tags: remove
