---
 - hosts: pgaserver
   remote_user: normaluser
   become: yes
   become_method: sudo
   become_user: root
   gather_facts: yes
   connection: ssh

   tasks:
           - name: Update the server
             shell: |
                     apt-get update
             args:
                     warn: false

           - name: Install wget, sudo, curl, tcpdump, net-tools, vim, iputils-ping, python2
             apt:
                     name: "{{item}}"
                     state: present
             loop:
                     - wget
                     - sudo
                     - curl
                     - tcpdump
                     - net-tools
                     - vim
                     - iputils-ping
                     - python2

           - name: Getting the node-exporter package
             shell: |
                     echo "deb https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list
                     wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
                     apt-get update
             args:
                     warn: false

           - name: Starting the grafana service
             service:
                     name: grafana-server
                     state: started

