---
 - hosts: elkserver
   remote_user: normaluser
   become: yes
   become_method: sudo
   become_user: root
   gather_facts: yes
   connection: ssh

   tasks:
           - name: Update the server
             shell: |
                     apt-get update
             args:
                     warn: false

           - name: Install gnupg, wget, sudo, curl, tcpdump, net-tools, vim, iputils-ping
             apt:
                     name: "{{item}}"
                     state: present
             loop:
                     - gnupg
                     - wget
                     - sudo
                     - curl
                     - tcpdump
                     - net-tools
                     - vim
                     - iputils-ping
                     - apt-transport-https

           - name: Getting the elasticsearch package
             shell: |
                     wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
                     echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee  /etc/apt/sources.list.d/elastic-7.x.list
             args:
                     warn: false

           - name: Updating the server again
             shell: |
                    apt-get update
             args:
                     warn: false

           - name: Installing Kibana
             apt:
                     name: kibana
                     state: present

           - name: Taking a backup of kibana configuration file
             copy:
                     src: /etc/kibana/kibana.yml
                     dest: /etc/kibana/kibana.yml_orig
                     remote_src: yes

           - name: Copying kibana configuration file
             copy:
                     src: conf/kibana.yml
                     dest: /etc/kibana/kibana.yml

           - name: Starting the Kibana service
             service:
                     name: kibana
                     state: started
