---
 - hosts: elkserver
   remote_user: normaluser
   become: yes
   become_method: sudo
   become_user: root
   gather_facts: yes
   connection: ssh

   tasks:
           - name: Update server
             shell: |
                     apt-get update
             args:
                     warn: false

           - name: Install gnupg, openssh-server, rsyslog, wget, sudo, curl, tcpdump, telnet, net-tools, vim, iputils-ping
             apt:
                     name: "{{item}}"
                     state: present
             loop:
                     - gnupg
                     - openssh-server
                     - rsyslog
                     - wget
                     - sudo
                     - curl
                     - tcpdump
                     - telnet
                     - net-tools
                     - vim
                     - iputils-ping
                     - apt-transport-https

           - name: Getting the elasticsearch package
             shell: |
                     wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
                     echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee  /etc/apt/sources.list.d/elastic-7.x.list
             args:
                     warn: false

           - name: Updating the server again
             shell: |
                    apt-get update
             args:
                     warn: false

           - name: Running dpkg command
             shell: |
                    dpkg --configure -a
             args:
                     warn: false

           - name: Installing logstash
             apt:
                     name: logstash
                     state: present

           - name: Copying the beats-input configuration file
             copy:
                     src: conf/beats-input.conf
                     dest: /etc/logstash/conf.d/beats-input.conf

           - name: Copying ssh-auth-filter.conf configuration file
             copy:
                     src: conf/ssh-auth-filter.conf
                     dest: /etc/logstash/conf.d/ssh-auth-filter.conf

           - name: Copying elasticsearch-output.conf configuration file
             copy:
                     src: conf/elasticsearch-output.conf
                     dest: /etc/logstash/conf.d/elasticsearch-output.conf


           - name: Starting the logstash Service
             service:
                     name: logstash
                     state: started
