---
 - hosts: webserver
   remote_user: normaluser
   become: yes
   become_method: sudo
   become_user: root
   gather_facts: yes
   connection: ssh

   tasks:
           - name: Update the server
             shell: |
                     apt-get update
             args:
                     warn: false

           - name: Install wget, sudo, curl, tcpdump, net-tools, vim, iputils-ping, python2
             apt:
                     name: "{{item}}"
                     state: present
             loop:
                     - wget
                     - sudo
                     - curl
                     - tcpdump
                     - net-tools
                     - vim
                     - iputils-ping
                     - python2

           - name: Getting the node-exporter package
             shell: |
                     wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
                     tar -xzf node_exporter-1.5.0.linux-amd64.tar.gz
                     sudo useradd -s /sbin/nologin prometheus
             args:
                     warn: false

           - name: Copying node_exporter.service file
             copy:
                     src: conf/node_exporter.service
                     dest: /etc/systemd/system/node_exporter.service

           - name: Copying systemctl file
             copy:
                     src: conf/systemctl.py
                     dest: /usr/bin/systemctl

           - name: Running some extra steps
             shell: |
                     chmod 755 /usr/bin/systemctl
                     sudo systemctl daemon-reload
             args:
                     warn: false


           - name: Starting the node_exporter service
             service:
                     name: node_exporter
                     state: started
