---
 - hosts: webserver
   remote_user: normaluser
   become: yes
   become_method: sudo
   become_user: root
   gather_facts: yes
   connection: ssh

   tasks:
           - name: Update server
             shell: |
                     apt-get update
             args:
                     warn: false

           - name: Install gnupg, openssh-server, rsyslog, wget, sudo, curl, tcpdump, telnet, net-tools, vim, iputils-ping
             apt:
                     name: "{{item}}"
                     state: present
             loop:
                     - gnupg
                     - openssh-server
                     - rsyslog
                     - wget
                     - sudo
                     - curl
                     - tcpdump
                     - telnet
                     - net-tools
                     - vim
                     - iputils-ping
                     - apt-transport-https

           - name: Getting the elasticsearch package
             shell: |
                     wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
                     echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee  /etc/apt/sources.list.d/elastic-7.x.list
             args:
                     warn: false

           - name: Updating the server again
             shell: |
                    apt-get update
             args:
                     warn: false

           - name: Installing filebeat
             apt:
                     name: filebeat
                     state: present

           - name: Taking a backup of filebeat configuration file
             copy:
                     src: /etc/filebeat/filebeat.yml
                     dest: /etc/filebeat/filebeat.yml_orig
                     remote_src: yes

           - name: Copying filebeat configuration file
             copy:
                     src: conf/filebeat.yml
                     dest: /etc/filebeat/filebeat.yml

           - name: Enabling system module within filebeat
             shell: |
                    filebeat modules enable system
             args:
                     warn: false


           - name: Taking a backup of system module configuration file
             copy:
                     src: /etc/filebeat/modules.d/system.yml
                     dest: /etc/filebeat/modules.d/system.yml_orig
                     remote_src: yes

           - name: Copying system module configuration
             copy:
                     src: conf/system.yml
                     dest: /etc/filebeat/modules.d/system.yml

           - name: Filebeat setup command
             shell: |
                    filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["elkserver:9200"]'
             args:
                     warn: false


           - name: Starting the Filebeat Service
             service:
                     name: filebeat
                     state: started
