---
 - hosts: logstash
   remote_user: normaluser
   become: yes
   become_method: sudo
   become_user: root
   gather_facts: yes
   connection: ssh

   tasks:
           - name: Update and upgrade the server
             shell: |
                     apt-get update && apt-get upgrade -y
             args:
                     warn: false

           - name: Install gnupg, wget, sudo, curl, tcpdump, net-tools, vim, iputils-ping, Java packages
             apt:
                     name: "{{item}}"
                     state: present
             loop:
                     - gnupg
                     - wget
                     - sudo
                     - curl
                     - tcpdump
                     - net-tools
                     - vim
                     - iputils-ping
                     - default-jdk
                     - openjdk-8-jre
                     - apt-transport-https

           - name: Getting the elasticsearch package
             shell: |
                     wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
                     echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee  /etc/apt/sources.list.d/elastic-7.x.list
             args:
                     warn: false

           - name: Updating the server again
             shell: |
                    apt-get update
             args:
                     warn: false

           - name: Running a dpkg command
             shell: |
                    dpkg --configure -a
             args:
                     warn: false

           - name: Installing Logstash
             apt:
                     name: logstash
                     state: present

           - name: copying the input conf
             copy:
                     src: conf/beats-input.conf
                     dest: /etc/logstash/conf.d/beats-input.conf

           - name: Copying the ssh-auth-filter
             copy:
                     src: conf/ssh-auth-filter.conf
                     dest: /etc/logstash/conf.d/ssh-auth-filter.conf

           - name: Copying the elasticsearch-output
             copy:
                     src: conf/elasticsearch-output.conf
                     dest: /etc/logstash/conf.d/elasticsearch-output.conf

           - name: Starting the Logstash service
             service:
                     name: logstash
                     state: started
